brand:
  name: Orion's Tattoo Portfolio
menu-string: Menu

nav:
  - title: Portfolio
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Testimonials
    url: '#Testimonials'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Orion's Tattoo Portfolio 2018

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'
  - icon: fa fa-instagram
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
